name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Instala as dependências npm
      - name: Install dependencies
        run: npm install
      # Start a aplicação (se necessário)
      - name: Start the app
        run: npm start
      # Executa os testes do Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v6
